export const ASSETS = {
  LOGO: "/assets/logo.png",
  IL_SOFTWARE: "/assets/il_software_developer.png",
  IL_MOBILE_APP: "/assets/il_mobile.png",
  IL_WEB_DEV: "/assets/il_web.png",
  IL_UIUX: "/assets/il_design.png",
  HOME_ORNAMENT: "/assets/home_ornament.png",
  OVERVIEW_IMAGE: "/assets/overview_image.png",
  TECH_STACK: "/assets/tech.png",
  TECH_MOBILE: "/assets/tech-mobile.png",
  IMG_MOBILE_DEV: "/assets/img_mobile_dev.png",
  IMG_UI_DESIGN: "/assets/img_ui_design.png",
  IMG_WEB_DEV: "/assets/img_web_dev.png",
  OG_IMAGE_DEFAULT: "/assets/og_image.png",
};
